[versions]
shadow = "8.3.0"
blossom = "1.3.1"
publish = "0.8.4"
moddevgradle = "2.0.78"
forgegradle = "[6.0,6.2)"
loom = "1.10-SNAPSHOT"
licenser = "0.6.1"

[plugins]
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
publish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "publish" }
moddevgradle = { id = "net.neoforged.moddev", version.ref = "moddevgradle" }
forgegradle = { id = "net.minecraftforge.gradle", version.ref = "forgegradle" }
loom = { id = "fabric-loom", version.ref = "loom" }
licenser = { id = "org.cadixdev.licenser", version.ref = "licenser" }